title: "metteko.net"
description: "Personal website of Ward (metteko)."
theme: minima
skin: dark      
permalink: /blog/:title/

header_pages:
  - index.html
  - blog.html

collections:
  posts:
    output: true
    permalink: /blog/:title/

social_links:
  github: "https://github.com/metteko"
  instagram: "https://www.instagram.com/ward.vsteenwinkel/"
  email: "mailto:ward.vanst@gmail.com"
