title: "metteko.net"
description: "Personal website of Ward (metteko)."
theme: minima
skin: dark      
permalink: /blog/:title/

header_pages:
  - index.html
  - blog.html

author:
  name: Ward Van Steenwinkel
  email: "ward.vanst@gmail.com"

social:
  github: metteko
  instagram: ward.vsteenwinkel
  discord: "1051856127295492147"
