title: "metteko.net"
description: "Personal website of Ward (metteko)."
theme: minima      
permalink: /blog/:title/

header_pages:
  - index.html
  - blog.html

minima:
  - title: Metteko's GitHub
     icon: github
     url: "https://github.com/metteko"
  - skin: dark


# author:
#   name: Ward Van Steenwinkel
#   email: "ward.vanst@gmail.com"

# social:
#   github: metteko
#   instagram: ward.vsteenwinkel
#   discord: "1051856127295492147"
